# Generated by Django 5.0.4 on 2024-06-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='updated_at',
        ),
    ]
